#ifndef POKEPLATINUM_STRUCT_02095E80_T_H
#define POKEPLATINUM_STRUCT_02095E80_T_H

#include <nitro/fx/fx.h>
#include <nnsys.h>

#include "struct_decls/struct_0202B370_decl.h"
#include "struct_decls/struct_02095E80_decl.h"
#include "struct_defs/chatot_cry.h"
#include "struct_defs/struct_02095E80_sub1.h"

#include "applications/pokemon_summary_screen/main.h"
#include "field/field_system_decl.h"
#include "overlay088/struct_ov88_0223C370.h"
#include "overlay088/struct_ov88_0223C8AC.h"

#include "bg_window.h"
#include "list_menu.h"
#include "menu.h"
#include "message.h"
#include "overlay_manager.h"
#include "pal_pad.h"
#include "party.h"
#include "savedata.h"
#include "sprite.h"
#include "sprite_resource.h"
#include "sprite_util.h"
#include "strbuf.h"
#include "string_list.h"
#include "string_template.h"
#include "sys_task_manager.h"

// union room trade data
struct UnionTradeData {
    FieldSystem *fieldSystem;
    SaveData *saveData;
    UnkStruct_ov88_playerData *playerData;
    PokemonSummary pokemonSummary;
    int isChatot;
    ApplicationManager *appMan;
    int unk_44;
    int unk_48;
    int currentTradeStep;
    int unk_50;
    int unk_54;
    int unk_58;
    int unk_5C;
    int unk_60[2];
    int unk_68;
    BOOL unk_6C;
    UnkStruct_02095E80_sub1 unk_70;
    // 0 is player's, 1 is friend's
    int selectedMonId[2];
    u16 unk_90;
    u16 unk_92[5][17];
    u16 unk_13C;
    u16 unk_13E;
    int unk_140;
    u16 unk_144[3];
    u32 unk_14C[2];
    u32 unk_154[2][3];
    int unk_16C;
    int unk_170;
    BgConfig *bgConfig;
    StringTemplate *tradeStrTemplate;
    StringTemplate *nicknameTemplate;
    StringTemplate *stringTemplate2;
    MessageLoader *tradeMessages;
    Strbuf *unusedStringBuffer;
    Strbuf *trainerName;
    Strbuf *itemMessage;
    SpriteList *spriteList;
    G2dRenderer renderer;
    SpriteResourceCollection *unk_324[4];
    SpriteResource *spriteResource[2][4];
    SpriteResourcesHeader resourceHeader;
    SpriteResourcesHeader unk_378;
    Sprite *sprites[14];
    Sprite *partySprites[12];
    Sprite *heldMailSprites[12];
    Sprite *ballCapsuleSprites[12];
    // the big sprite shown for the selected mon on the bottom screen.
    Sprite *pokemonBattleSprites[6];
    Sprite *unk_47C;
    SysTask *unk_480[7];
    Window windows[34];
    Menu *unk_6BC;
    StringList *options;
    Menu *pokemonActionMenu;
    int unk_6C8;
    int unused;
    int unk_6D0;
    int unk_6D4;
    VecFx32 unk_6D8[2];
    int unk_6F0;
    Trade_PokemonData tradePokemonData[13];
    int unk_7B8;
    int unk_7BC;
    int unk_7C0;
    int unk_7C4[7];
    void *unk_7E0;
    NNSG2dCharacterData *unk_7E4;
    void *unk_7E8_pokemon[12];
    NNSG2dCharacterData *charData[12];
    u8 unk_848[2][3200];
    PokemonSpriteTemplate unk_2148[2];
    int unk_2168;
    u8 unk_216C[256];
    int (*nextFunction)(Trade *);
    Party *playerParty;
    Party *friendParty;
    ChatotCry *unk_2278;
    PalPad *playerPalPad;
    PalPad friendPalPad;
    int unk_2308;
    int unk_230C;
    int unk_2310;
    int unk_2314;
    int unk_2318;
    VecFx32 unk_231C[2];
    VecFx32 unk_2334[2];
    u8 unk_234C[2][1424];
    u8 chatotCry[2][1004];
    int unk_3644[32];
    int friendNetId;
    int friendRosterSlot;
    StringTemplate *nameTemplate;
    MessageLoader *palPadMessages;
    StringList *friendList;
    ListMenu *friendRosterMenu;
    Window friendRosterWindow;
    WiFiList *wifiList;
    int unk_36F0;
    int unk_36F4;
    int lastSentData;
    int lastSentCmd;
    void *waitingWindow;
    int unk_3704;
    int unk_3708;
};

#endif // POKEPLATINUM_STRUCT_02095E80_T_H
